global:
  scrape_interval: 15s
  external_labels:
    server_name: site:prod
scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'prometheus_node'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9100']
  - job_name: mysql # To get metrics about the mysql exporter’s targets
    params:
      auth_module: [client.servers]
    static_configs:
      - targets:
        - unix:///run/mysqld/mysqld.sock
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        # The mysqld_exporter host:port
        replacement: localhost:9104
  - job_name: blackbox-http
    metrics_path: /probe
    params:
      module:
      - http_2xx
    relabel_configs:
    - source_labels:
      - __address__
      target_label: __param_target
    - source_labels:
      - __param_target
      target_label: instance
    - replacement: localhost:9115
      target_label: __address__
    static_configs:
    - targets:
      - https://chobod.ru
  - job_name: "Nginx"
    metrics_path: /nginx_stats
    static_configs:
    - targets: ['79.133.182.241:9113']
  - job_name: "php-fpm"
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9253']
alerting:
  alertmanagers:
  - static_configs:
    - targets: ['localhost:9093']
rule_files:
  - "rules.yml"
remote_write:
  - url: http://79.133.182.241:8428/api/v1/write
    queue_config:
      max_samples_per_send: 10000
      capacity: 20000
      max_shards: 30
root@chobod:/etc/syst